baseURL = '/'
languageCode = 'en-us'
title = "Theo's Tech Notes"
theme = "terminal"
enableGitInfo = true

[frontmatter]
date = [":git", "date", "lastmod"]
lastmod = ["lastmod", ":git", "date", "publishDate"]
publishDate = ["publishDate", "date"]
expiryDate = ["expiryDate"]

[params]
    contentTypeName = "posts"
    themeColor = "blue"
    fullWidthTheme = true
    centerTheme = true
    showLastUpdated =  true

[languages]
  [languages.en]
    languageName = "English"
    [languages.en.params.logo]
      logoText = "Theo's Tech Notes"
      logoHomeLink = "/"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

