baseURL = '/'
languageCode = 'en-us'
title = "Theo's Tech Notes"
theme = "terminal"
[params]
    contentTypeName = "posts"
    themeColor = "blue"
    fullWidthTheme = true
    centerTheme = true
    showLastUpdated =  true
    enableGitInfo = true

[languages]
  [languages.en]
    languageName = "English"
    [languages.en.params.logo]
      logoText = "Theo's Tech Notes"
      logoHomeLink = "/"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

